Make touch to be an instance method
Since `Store` defines `touch` as an instance method, typescript throws on this:

```
node_modules/connect-typeorm/out/app/TypeormStore/TypeormStore.d.ts:38:5 - error TS2425: Class 'Store' defines instance member property 'touch', but extended class 'TypeormStore' defines it as instance member function.
```